
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: 8080
      ENV: production
      VOLUMES_PATH: /app/volumes
      GIN_MODE: release
      DATABASE_PATH: /app/data/data.db
    volumes:
      - ./volumes:/app/volumes
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock